# Site settings1
title: Mauricio Urraco11
description: Jekyll Theme Minimal Resume1
# baseurl: "" # the subpath of your site, e.g. /blog1
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br1

# User settings1
username: Mauricio Urraco1
user_description: 1
user_title: Software Engineer1
email: mauriurraco@gmail.com1
# twitter_username: lorem_ipsum1
# github_username:  lorem_ipsum1
# gplus_username:  lorem_ipsum1
1
# Google-analytics1
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
